services:
  app:
    build: .
    container_name: flyrank-api

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - db

    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:16

    container_name: flyrank-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flyrank

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: